### ISSUE TITLE
Need option to run only at execution root

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/buildmetadata-maven-plugin#10]
See https://github.com/jdcasey/project-sources-maven-plugin/blob/master/src/main/java/org/commonjava/maven/plugins/projectsrc/ProjectSourcesGoal.java#L223 for an example of how this can be done.

We need to be able to generate the properties for the build only in the root project for the current build, rather than generating for each module that gets built.

**Comment by sbadakhc** [comment]
Is this still and issue?  I.5.1 was just released so just checking.

**Comment by rnc** [comment]
I think this is resolved now ; closing
