### ISSUE TITLE
Clear the association with smartics.eu

### ISSUE THREAD

**Issue by WhiteHatTux** [release-engineering/buildmetadata-maven-plugin#36]
Hi,

in this project you refer to this page:
http://www.smartics.eu/buildmetadata-maven-plugin/
Checking back on that page i see this usage information:
http://www.smartics.eu/buildmetadata-maven-plugin/usage.html
Which refers to the de.smartics groupId and going through their page this leads to their svn repository:
https://www.smartics.eu/svn/public/maven/buildmetadata-maven-plugin/trunk/

Would you mind clearing this up and putting your association to smartics somewhere in the readme maybe. 

Thanks in advance
WhiteHatTux

**Comment by sbadakhc** [comment]
Hi,

This association can be removed as required by editing the item and changing the link to:
https://github.com/release-engineering/buildmetadata-maven-plugin

I see edit this option on my fork of the project but not on the rel-eng fork.  John can you see if you can edit this?  There should be an "Edit" link next to the title.

**Comment by jdcasey** [comment]
I've removed smartics from the notes in the README. Is that what we need to do? I'm a little confused about "editing the item"...

**Comment by jdcasey** [comment]
also removed from the description for the repository on GitHub.

**Comment by rnc** [comment]
This is a fork of upstream. Smartics have now placed their code on github and deployed to central : https://github.com/smartics/buildmetadata-maven-plugin. We intend to return changes upstream.

I think this ticket could be closed?

**Comment by WhiteHatTux** [comment]
I think a quick note about the upstream project should be enough. I was just a little confused, when i looked at the different pages and jumped around different locations and websites and opened this ticket to clear the relation of upstream-downstream and of the project, that deploys to central. 

After that the ticket can be closed.

**Comment by rnc** [comment]
@WhiteHatTux Ok, thanks. Originally we forked it in order to deploy to central (as that hadn't been done) and add our own fixes outside of the timeline of upstream.

**Comment by rnc** [comment]
Fixed by #39
